# This rule is not used by the project bootc-load-balancer-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the config.bootc-lb.syn.tools.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bootc-load-balancer-controller
    app.kubernetes.io/managed-by: kustomize
  name: loadbalancerconfig-editor-role
rules:
- apiGroups:
  - config.bootc-lb.syn.tools
  resources:
  - loadbalancerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.bootc-lb.syn.tools
  resources:
  - loadbalancerconfigs/status
  verbs:
  - get
