---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.bootc-lb.syn.tools
  resources:
  - loadbalancerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.bootc-lb.syn.tools
  resources:
  - loadbalancerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - config.bootc-lb.syn.tools
  resources:
  - loadbalancerconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
