apiVersion: config.bootc-lb.syn.tools/v1alpha1
kind: LoadBalancerConfig
metadata:
  labels:
    app.kubernetes.io/name: bootc-load-balancer-controller
    app.kubernetes.io/managed-by: kustomize
  name: loadbalancerconfig-sample
spec:
  # TODO(user): Add fields here
